// Generated by Binserde 0.1.0

import { Arr, Base, Bool, Int8, Int16, Int32, Int64, Int128, Option, String, Uint8, Uint16, Uint32, Uint64, Uint128, Float32, Float64, Vec } from 'bincoder';

export class ArrayTest extends Base {
  a: Arr<Uint8, 32>;
  b: Arr<Test5, 2>;

  constructor(a: Arr<Uint8, 32> = new Arr(Uint8, 32), b: Arr<Test5, 2> = new Arr(Test5, 2)) {
    super()
    this.a = a;
    this.b = b;
  }
}

export class Test5 extends Base {
  a: Uint16;

  constructor(a: Uint16 = new Uint16()) {
    super()
    this.a = a;
  }
}
