// Generated by Binserde 0.1.0

import { Arr, Base, Bool, Int8, Int16, Int32, Int64, Int128, Option, String, Uint8, Uint16, Uint32, Uint64, Uint128, Float32, Float64, Vec } from 'bincoder';

export class BasicTypes extends Base {
  a: Bool;
  b: Uint8;
  c: Uint16;
  d: Uint32;
  e: Uint64;
  f: Uint128;
  g: Int8;
  h: Int16;
  i: Int32;
  j: Int64;
  k: Int128;
  l: Float32;
  m: Float64;
  n: String;

  constructor(a: Bool = new Bool(), b: Uint8 = new Uint8(), c: Uint16 = new Uint16(), d: Uint32 = new Uint32(), e: Uint64 = new Uint64(), f: Uint128 = new Uint128(), g: Int8 = new Int8(), h: Int16 = new Int16(), i: Int32 = new Int32(), j: Int64 = new Int64(), k: Int128 = new Int128(), l: Float32 = new Float32(), m: Float64 = new Float64(), n: String = new String()) {
    super()
    this.a = a;
    this.b = b;
    this.c = c;
    this.d = d;
    this.e = e;
    this.f = f;
    this.g = g;
    this.h = h;
    this.i = i;
    this.j = j;
    this.k = k;
    this.l = l;
    this.m = m;
    this.n = n;
  }
}
