// Generated by Binserde 0.1.0

import { Arr, Base, Bool, Int8, Int16, Int32, Int64, Int128, Option, String, Uint8, Uint16, Uint32, Uint64, Uint128, Float32, Float64, Vec } from 'bincoder';

export class Hello extends Base {
  a: Uint8;
  b: Uint16;

  constructor(a: Uint8 = new Uint8(), b: Uint16 = new Uint16()) {
    super()
    this.a = a;
    this.b = b;
  }
}
