// Generated by Binserde 0.1.0

import { Base, Bool, Int8, Int16, Int32, Int64, Int128, Option, String, Uint8, Uint16, Uint32, Uint64, Uint128, Float32, Float64, Vec } from 'bincoder';

export class Test1 extends Base {
  a: Test2;

  constructor(a: Test2 = new Test2()) {
    super()
    this.a = a;
  }
}

export class Test2 extends Base {
  a: Uint16;

  constructor(a: Uint16 = new Uint16()) {
    super()
    this.a = a;
  }
}
