// Generated by Binserde 0.1.0

import { Base, Bool, Int8, Int16, Int32, Int64, Int128, Option, String, Uint8, Uint16, Uint32, Uint64, Uint128, Float32, Float64, Vec } from 'bincoder';

export class Test3 extends Base {
  a: Vec<Uint32>;
  b: Vec<Test3>;

  constructor(a: Vec<Uint32> = new Vec(Uint32), b: Vec<Test3> = new Vec(Test3)) {
    super()
    this.a = a;
    this.b = b;
  }
}

export class Test4 extends Base {
  c: Bool;

  constructor(c: Bool = new Bool()) {
    super()
    this.c = c;
  }
}
